language: node_js
node_js:
  - v5
  - v4
  - '0.12'
  - '0.10'
evn:
  - NPM_VERSION=3.5

before_install:
  - npm install -g npm@$NPM_VERSION
  - npm --version
  - npm install -g mocha

script: "npm test"